name: Build And Push Docker Image[ghcr.io]

on:
  workflow_call:
    inputs:
      image:
        description: image name
        required: true
        type: string
      dockerfile:
        description: path to Dockerfile
        required: false
        type: string
        default: Dockerfile
      tags:
        description: image tags
        required: false
        type: string
        default: |
          type=semver,pattern={{version}}
          type=ref,event=branch,suffix=-{{sha}}
          type=ref,event=pr,prefix=pr-

jobs:
  build:
    name: Build And Push Docker Image
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout target repository
        id: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        id: builder
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.7.1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ inputs.image }}
          flavor: ${{ inputs.flavor }}
          tags: ${{ inputs.tags }}

      - name: Login to Github Container Registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        id: build-push
        uses: docker/build-push-action@v2
        with:
          file: ${{ inputs.dockerfile }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
