name: Github Actions Version Updater

on:
  schedule:
    - cron: "0 6 * * 5"

jobs:
  terraform-updater:
    name: actions version updater(related terraform)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repositry:
          - mintak21/terraform
        package:
          - terraform
          - tflint
          - tfsec
        include:
          - package: terraform
            repository: "hashicorp/terraform"
          - package: tflint
            repository: "terraform-linters/tflint"
          - package: tfsec
            repository: "aquasecurity/tfsec"
      fail-fast: false
    env:
      COMITTER: actions-version-updater

    steps:
      - name: Get Latest Version
        id: latest-versions
        run: |
          latest=$(curl -H "Content-Type: application/json" https://api.github.com/repos/${{ matrix.repository }}/releases | jq -r '.[] | select(.prerelease|not) | .name' | sort -rn | head -n 1 | sed "s/v//g")
          echo target version is ${latest}
          echo "version=${latest}" >> $GITHUB_ENV

      - name: Checkout target repository
        id: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.target_repositry }}
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: Create commits
        id: commit
        run: |
          sed -i -e "s/${{ matrix.package }}=.*/${{ matrix.package }}=${{ env.version }}/" .github/workflows/.versions
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          commit-message: ":robot: automatic update ${{ matrix.package }} to ${{ env.version }}"
          committer: ${{ env.COMITTER }} <${{ env.COMITTER }}@users.noreply.github.com>
          author: ${{ env.COMITTER }} <${{ env.COMITTER }}@users.noreply.github.com>
          signoff: true
          branch: versionup/github_actions/main/${{ matrix.package }}-v${{ env.version }}
          delete-branch: true
          title: ":arrow_up: Bump ${{ matrix.package }} to ${{ env.version }}"
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/mintak21/actions-version-updater/actions/runs/${{ github.run_id }}
          labels: |
            github-actions
            ${{ matrix.package }}
          reviewers: mintak21
          draft: false

  gcloud-updater:
    name: actions version updater(gcloud)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repositry:
          - mintak21/terraform
        package:
          - gcloud
      fail-fast: false
    env:
      COMITTER: version-update-bot
      AUTHOR: github-actions

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0

      - name: Get Latest Version
        id: latest-version
        run: |
          latest=$(gsutil ls gs://cloud-sdk-release/ | grep linux-x86_64 | sed -e "s/^.*google-cloud-sdk-\(.*\)-linux.*.gz$/\1/" | sort -rn | head -n 1)
          echo target version is ${latest}
          echo "version=${latest}" >> $GITHUB_ENV

      - name: Checkout target repository
        id: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.target_repositry }}
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Create commits
        id: commit
        run: |
          sed -i -e "s/${{ matrix.package }}=.*/${{ matrix.package }}=${{ env.version }}/" .github/workflows/.versions

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          commit-message: ":robot: automatic update ${{ matrix.package }} to ${{ env.version }}"
          committer: ${{ env.COMITTER }} <${{ env.COMITTER }}@users.noreply.github.com>
          author: ${{ env.COMITTER }} <${{ env.COMITTER }}@users.noreply.github.com>
          signoff: true
          branch: versionup/github_actions/main/${{ matrix.package }}-v${{ env.version }}
          delete-branch: true
          title: ":arrow_up: Bump ${{ matrix.package }} to ${{ env.version }}"
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/mintak21/actions-version-updater/actions/runs/${{ github.run_id }}
          labels: |
            github-actions
            ${{ matrix.package }}
          reviewers: mintak21
          draft: false
